### ISSUE TITLE
 Class 'simple_html_dom' not found

### ISSUE THREAD

**Issue by Mutuh** [erivello/SimpleHtmlDomBundle#1]
I tried to use SimpleHtmlDomBundle with Symfony 2.0
Got an error `PHP Fatal error:  Class 'simple_html_dom' not found in app\cache\dev\appDevDebugProjectContainer.php`.
I think something wrong with `<parameter key="simple_html_dom.class">simple_html_dom</parameter>` in config.xml

**Comment by Mutuh** [comment]
I fixed error by adding `require_once __DIR__.'/../vendor/bundles/Erivello/SimpleHtmlDomBundle/lib/simple_html_dom.php';` to the autoload.php

**Comment by erivello** [comment]
Hi Mutuh,
sorry. This error is still exists?
