### ISSUE TITLE
Please update simplehtmldom to the latest version

### ISSUE THREAD

**Issue by vivianspencer** [erivello/SimpleHtmlDomBundle#5]
The version of simplehtmldom you've included in this bundle was released in 2008, please update to the latest version http://sourceforge.net/p/simplehtmldom/code/HEAD/tree/trunk/simple_html_dom.php

**Comment by ghost** [comment]
@vivianrspencer Would you please commit your changes and add a pull request, so the author could update it?

**Comment by ghost** [comment]
@erivello Would you please look into updating SimpleHtmlDom to the latest version?

**Comment by erivello** [comment]
@nkornev and @vivianrspencer i'll update SimpleHtmlDom to the latest version as soon as possible, i think within a few days.

**Comment by erivello** [comment]
@nkornev and @vivianrspencer i've updated the library to the latest version. Does it work?

**Comment by vivianspencer** [comment]
@erivello Works great, thanks
